version: '3'
services:
  mysql:
    image: mysql:8.0.32
    restart: unless-stopped
    command: --max-connections 2048
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: watermill
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
