version: '3.9'
services:
  postgres:
    image: postgres:15.2
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: watermill
      POSTGRES_DB: watermill
      POSTGRES_PASSWORD: "password"
